title: "Eric's Blog"
languageCode: "en-US"
baseurl: "https://ericbaranowski.netlify.com"
copyright: "Copyright (c) 2019. All rights reserved.  <a href='https://www.kulado.com/'>Kulado Inc.</a>"
theme: "hugo-rapid-theme"
MetaDataFormat: "yaml"
canonifyurls: true
builddrafts: false
PaginatePath: paginator
pygmentsStyle: "default"
pygmentsUseClasses: true
disablePathToLower: true 
hasCJKLanguage: true
permalinks:
  posts: /:year/:month/:day/:slug/

outputs:
  home:
    - "RSS"
    - "HTML"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

Taxonomies:
  tag: "tags"
  category: "categories"

params:
  GitHubUser: "ericbaranowski"
  SidebarRecentLimit: 5
  DateForm : "2006-01-02"
  Tagline: "An entrepreneurs's thoughts and research"
  Description: "If you do not feel time is not enough, you probably are idling in."
  Keywords: "Eric Baranowski,Programmer,Thinking,Developer,Technology"
  Categories:
    - "Research"
    - "Tech articles"
    - "Perception"
menu:
  main:
      - Name: "Archive"
        Pre: "<i class='fa fa-heart'></i>"
        Weight: -110
        Identifier: "post"
        URL: "/post/"
      - Name: "About me"
        Pre: "<i class='fa fa-road'></i>"
        Identifier: "about"
        Weight: -100
        URL: "/about/"
author:
  name: "Eric"

images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
